#!/usr/bin/env bash

# Dockerfiles for php-cli
for version in php56 php70 php71 php72; do
    lib="$version/cli"
    target="$lib/Dockerfile"

    cat \
        src/autogenerated \
        src/baseimage_${version}-cli \
        src/php_extensions \
        src/php_ini_opcache \
        src/composer \
        src/workdir_with_user \
        > $target
    echo "Created $target"
done

# Dockerfiles for php-apache
for version in php56 php70 php71 php72; do
    lib="$version/apache"
    target="$lib/Dockerfile"

    cp src/apache.conf $lib
    cat \
        src/autogenerated \
        src/baseimage_${version}-apache \
        src/php_extensions \
        src/php_ini_opcache_develop \
        src/apache \
        src/composer \
        src/workdir_without_user \
        > $target

    echo "Created $target"
done

# Dockerfiles having pre installed Git module
# for version in php70 php71 php72; do
version="php72"
lib="$version/apache"
target="$lib/Dockerfile-clone-repo-make-install"

cp src/apache.conf $lib
cat \
    src/autogenerated \
    src/baseimage_anax-dev-${version}-apache \
    src/debian_base \
    src/clone_repo_make_install \
    > $target

echo "Created $target"
# done
